addzopeuser accepts custom location of zope.conf
zopefoundation/Zope pull request #1067
Opened 2022-10-19 14:32 UTC by jensens

Script `addzopeuser` accepts now parameter '-c' or '--configuration'. This allows passing in an custom location for the `zope.conf` file to use. If not specified behavior not altered.

On you request @pbauer 

I found it was possible already to specify the path setting an environment variable `ZOPE_CONF`. But I think it is more intuitive to pass it as a parameter.

While at it and because it simplifies the code and auto-documents the script I introduced usage of argparse here.

2022-10-19 14:38 UTC, davisagli commented
I don't like the inconsistency between using a named option here while existing scripts like zconsole take it as a positional arg.

On the other hand, I like it better as a named option.

Hmm. Not sure what to do.

2022-10-19 14:48 UTC, jensens commented
I first thought about making it positional, but its so counterintuitive and ugly... 

Really like `addzopeuser joe 123t4est instance/etc/zope.conf` ?

Would need to be the last arg in order to make it optional. 
More opinions on this? I can change it...

2022-10-19 14:51 UTC, davisagli commented
@jensens No, I think it's better the way you have it.

2022-10-20 13:26 UTC, jensens commented
It looks like the windows tests are a bit flaky...

2022-10-20 13:42 UTC, jensens commented
all green, who wants to review?

2022-10-20 13:49 UTC, ale-rt commented on CHANGES.rst
> +  If not specified, behavior is not not altered.
```suggestion
  If not specified, behavior is not altered.
```

2022-10-20 13:53 UTC, ale-rt reviewed
LGTM to me but there is a typo

2022-10-20 13:53 UTC, dataflake requested changes

2022-10-20 13:53 UTC, dataflake commented on docs/operation.rst
> +If it is located on a different location this can be specified by the `--configuration` option:
```suggestion
If it is located in a different location you can specify it with the `--configuration` option:
```

2022-10-20 13:53 UTC, dataflake commented on src/Zope2/utilities/adduser.py
> +        help="Zope configuration file",
```suggestion
        help="Path to Zope configuration file",
```

2022-10-20 14:22 UTC, dataflake approved these changes

2022-10-20 14:46 UTC, merged