FileUpload: use latin-1 as charset when nothing is passed.
zopefoundation/Zope pull request #1101
Opened 2023-03-07 23:54 UTC by mauritsvanrees

Without this change, some tests (and possibly live code) in Plone fail because they do not pass the new required `charset` parameter. See https://github.com/plone/buildout.coredev/pull/844
And see discussion that I just started here:
https://github.com/zopefoundation/Zope/pull/1094#issuecomment-1459047253

Also fixes an unclosed file in a test.

2023-03-08 07:37 UTC, d-maurer reviewed
As said in "https://github.com/zopefoundation/Zope/pull/1094#issuecomment-1459654636", I do not mind to make `charset` optional -- with any default argument.

Nevertheless, I think that instead the tests should get improved to correctly reflect the browser situation. For the browser, the `charset` is the form's charset, i.e. an input parameter. Usually, it will be the server's `default_encoding`, i.e. usually `utf-8` (and not `latin-1`).
Your PR chooses a default value such that sub optimal tests succeed, not the value which would typically be expected.

2023-03-08 10:24 UTC, mauritsvanrees commented
@d-maurer Thanks for your review, and your reply to my comment.
I have updated the code in this PR to use the `default_encoding`.

2023-03-09 06:02 UTC, dataflake approved these changes

2023-03-09 08:09 UTC, d-maurer requested changes

2023-03-09 08:29 UTC, mauritsvanrees commented on src/ZPublisher/HTTPRequest.py
> +    def __init__(self, aFieldStorage, charset=default_encoding):
Ah, good point.  Done.

2023-03-09 09:12 UTC, merged