Port of #933 to 4.x
zopefoundation/Zope pull request #935
Opened 2020-11-20 10:07 UTC by dataflake

I created a PR for this backport because it required an additional fix in response handling that I need some eyes on. The fix only affects Python 2 where the `setBody` method receives a body of type `io.BytesIO` sometimes, and the code would misinterpret that as one of the objects to raise the `NotFound`

2020-11-21 06:20 UTC, d-maurer requested changes
I think `BytesIO` should be handled elsewhere: The "normal" place to handle IO responses (and other advanced responses such as iterator responses) is `WSGIResponse.setBody`. This uses `isinstance(body, IOBase)` to recognize this case. Due to the definition of `IOBase` (near the start of `HTTPResponse`) it does not correctly recognize `BytesIO`.

In my view, we should fix the `IOBase` definition. Instead of
```python
if sys.version_info >= (3, ):
    from io import IOBase
else:
    IOBase = file  # NOQA
```
I propose
```python
from io import IOBase
if PY2:
    IOBase = (file, IOBase)
```

2020-11-23 07:11 UTC, icemac commented
Dieter's proposal sounds interesting but I do not feel competent for this PR.

2020-11-23 10:14 UTC, dataflake commented
@d-maurer Thank you for looking at this. Your suggestion makes a lot more sense. I only changed one aspect: I want to avoid shadowing the imported name `IOBase` with that tuple you suggested, so I created a separate variable.

2020-11-23 10:43 UTC, d-maurer approved these changes

2020-11-23 11:18 UTC, merged